export const WALLPAPERS = {
    'morning-mist': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/morning-mist.webp', focusX: 0.78, focusY: 0.5 },
    'cecilylove002': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/cecilylove002.webp', focusX: 0.5, focusY: 0.5 },
    'lucy-moon': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/lucy-moon.webp', focusX: 0.5, focusY: 0.5 },
    'moonlit-pine': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/moonlit-pine.webp', focusX: 0.82, focusY: 0.42 },
    'wukong': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/wukong.webp', focusX: 0, focusY: 0.5 },
    'dreamskin-2560x1440': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/dreamskin-2560x1440.webp', focusX: 0.28, focusY: 0.5 },
    'deepseek': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/deepseek.webp', focusX: 0.5, focusY: 0.5 },
    'mikuu-full-background': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/mikuu-full-background.webp', focusX: 0.5, focusY: 0.5 },
    'poster': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/poster.webp', focusX: 0.5, focusY: 0.5 },
    'reze': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/reze.webp', focusX: 0.5, focusY: 0.5 },
    'firefly': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/firefly.webp', focusX: 0.08, focusY: 0.5 },
    'juzizhoutou': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/juzizhoutou.webp', focusX: 0.5, focusY: 0.5 },
    'republic': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/republic.webp', focusX: 0.55, focusY: 0.5 },
    '111': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/111.webp', focusX: 0.67, focusY: 0.78 },
    'quiet-orbit': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/quiet-orbit.webp', focusX: 0.76, focusY: 0.5 },
    '123456': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/123456.webp', focusX: 0, focusY: 0.5 },
    'idea-engine': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/idea-engine.webp', focusX: 0.5, focusY: 0.5 },
    'forest': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/forest.webp', focusX: 0.5, focusY: 0.5 },
    'violet-evergarden': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/violet-evergarden.webp', focusX: 0.5, focusY: 0.45 },
    'claude-eva-warm': { url: 'https://raw.githubusercontent.com/nlqh7/dsh-dream-skin/master/wallpapers/claude-eva-warm.webp', focusX: 0.44, focusY: 0.38 },
};
//# sourceMappingURL=wallpapers.js.map